ser: null-terminated strings
getty-zig/json pull request #24
Opened 2022-09-03 09:09 UTC by Namek

#23

2022-09-03 13:58 UTC, ibokuri requested changes

2022-09-03 13:58 UTC, ibokuri commented on src/ser/impl/formatter/details/escape.zig
> +    var bytes = std.mem.sliceTo(input, 0);
Is it possible to make `bytes` `const` here? I don't believe it's modified anywhere in this function.

2022-09-03 13:58 UTC, ibokuri commented on src/ser/serializer.zig
> +            var slice = std.mem.sliceTo(value, 0);
Same here, can be this be made into a `const`?

2022-09-03 14:05 UTC, ibokuri commented
Looks like this change is failing the test case for `"\u{0}"`, which should be serialized as `"\"\\u0000\""`, not `""`.

2022-09-04 15:28 UTC, Namek commented
closing, as discussed in #23

2022-09-04 15:28 UTC, closed without merging